deploy:
  provider: pages
  skip-cleanup: true

sudo: required

os:
  - linux

before_install:
  - sudo apt install -y x11-apps fuse
  - sudo modprobe fuse
  - sudo chmod 666 /dev/fuse
  - sudo chown root:$USER /etc/fuse.conf

script:
  - wget https://github.com/Pext/Pext/releases/download/v0.18/Pext-x86_64.AppImage
  - chmod +x Pext-x86_64.AppImage
  - ./Pext-x86_64.AppImage --install-module https://raw.githubusercontent.com/Pext/pext_module_emoji/master/metadata.json
  - xvfb-run --server-args="-screen 0 800x600x24" ./Pext-x86_64.AppImage & sleep 5 && xwd -display :0 -root -out "/tmp/screenshot" >/dev/null && convert "/tmp/screenshot" "screenshot1.png"
  - xvfb-run --server-args="-screen 0 800x600x24" ./Pext-x86_64.AppImage --module pext.module.emoji & sleep 5 && xwd -display :0 -root -out "/tmp/screenshot" >/dev/null && convert "/tmp/screenshot" "screenshot2.png"
  - rm Pext-x86_64.AppImage
